# yaml-language-server: $schema=./node_modules/@mark-magic/cli/dist/config.schema.json
generate:
  - name: epub
    input:
      name: '@mark-magic/plugin-local'
      config:
        path: ./books/
    output:
      name: '@mark-magic/plugin-epub'
      config:
        path: ./dist/epub/珀耳塞福涅的华尔兹.epub
        metadata:
          id: 珀耳塞福涅的华尔兹
          title: 珀耳塞福涅的华尔兹
          creator: ErinPtah
          publisher: rxliuli
          language: zh-CN
          cover: ./books/assets/cover.jpeg
  - name: web
    input:
      name: '@mark-magic/plugin-local'
      config:
        path: ./books/
    output:
      name: '@mark-magic/plugin-docs'
      config:
        name: 珀耳塞福涅的华尔兹
        path: ./dist/docs/
        public: ./static/
        logo: /logo.jpeg
        nav:
          - text: GitHub
            link: https://github.com/liuli-moe/persephone-s-waltz.git
        giscus:
          repo: liuli-moe/persephone-s-waltz
          repoId: R_kgDOIxmT8Q
          category: Announcements
          categoryId: DIC_kwDOIxmT8c4CTlsO
          mapping: pathname
          reactionsEnabled: '1'
          emitMetadata: '0'
          inputPosition: bottom
          theme: dark
          lang: zh-CN
          crossorigin: anonymous
        gtag: G-YQC4Q53RM3
